### PR TITLE
Undefined variable fix

### PR DESCRIPTION
**Pull request by spookmango**
`content.path` was undefined causing a `TypeError` to be thrown when I ran the sample code.

### CODE REVIEW

**Comment by cyrilis** [comment]
Hi @spookmango ,
Thank you for your pull-request, but javascript file is generate from coffeescript file( index.js file  is generated from index.coffee), could you add the coffeescript file change too ? 😃 

Thanks!

**Comment by spookmango** [comment]
Updated it!

**Comment by pedrosanta** [comment]
👍  Nice one @spookmango.

**Comment by cyrilis** [comment]
Thanks @spookmango !

**Comment by spookmango** [comment]
Should there also be a version bump so people who were effected by this can `npm update`. 

I ran my project that used epub-gen on another machine and the bug fixed with this PR was present but not encountered so I suspect (without looking deeply into epub-gen's src) it was situational. 

But if I want to give my project to someone who is effected by the bug they'd still have to update epub-gen by hand.

**Comment by pedrosanta** [comment]
Hi @spookmango, yap, we still hadn't released an update. Sorry for the delay. 😀  I'm taking care of that now. Cheers!

**Comment by pedrosanta** [comment]
v0.0.14 released, you can go on now and update. 😏  Cheers!

**Pull request merged**
