### PR TITLE
add support to local files in images

### PR DESCRIPTION
**Pull request by jrpelegrina**
With the upgrade is possible to use images that are in place (for this the path must start with file: //

### CODE REVIEW

**Comment by cyrilis** [comment]
Hi @jrpelegrina ,

I've checked this pull-request, nice work! :+1: 

However, as you can see, we use coffeescript to generate javascript files in this project, so it will be appreciated if you could submit these changes in coffeescript with compiled javascirpts. If you are busy or really hate coffeescript, just tell me, I'll add the coffeescript code with your code. :smile: 

Thanks for your contribution!

**Comment by emagnier** [comment]
Thanks @jrpelegrina for your PR :+1: 

Also if you can (next time), add more details in the description of your PR (more informations, or examples). It's always better to understand what you are adding (or fixing), so it makes your code more easy to review.

And don't forget to update the README.md to explain what is now supported ;-)

Like @cyrilis is mentioning above, this module use Coffeescript.
I suggest you to use exactly the same version that was already used before to compile this module:
```
npm install -g coffee-script@1.7.1
```

**Comment by jrpelegrina** [comment]
Hi
I updated my push with what I suggested in the comments (update the README and has been encoded with CoffeeScript.

**Comment by cyrilis** [comment]
@jrpelegrina ,
Thanks for your contribution and patience. :smile: 
PR is accepted.
NPM package will update soon.

**Pull request merged**
